version: '3.6'

volumes:
  event_psql:
  event_redis:

networks:
  default:
    name: 'event_network'

services:
  db:
    image: postgres:11-alpine
    container_name: event_psql
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - event_psql:/var/lib/postgresql/data/

  redis:
    image: redis:alpine3.10
    container_name: event_redis
    ports:
      - ${REDIS_PORT}:6379